### PR TITLE
Add villains collection

### PR DESCRIPTION
**Pull request by jwfxpr**

### CODE REVIEW

**Comment by jwfxpr** [comment]
Contains three commits, one each for BBC and Villains collections (hopefully this should prevent merge conflicts with #1) and a third to correctly title case the Guardian collection name (this should solve the issue of Clarissa's missing position No. 4 in the [Guardian collection page](https://standardebooks.org/collections/the-guardians-best-100-novels-in-english-2015)).

**Comment by acabal** [comment]
This conflicts with #1, can you sort that out?

**Comment by jwfxpr** [comment]
Resolved. Sorry, didn't expect a conflict!

**Comment by acabal** [comment]
Thanks!

**Pull request merged**
