### PR TITLE
Quotes

### PR DESCRIPTION
**Pull request by bentley**
~~These letters use ‹› for what they call “turned comma.” The scans simply show normal quotes ([Letter 246](https://babel.hathitrust.org/cgi/pt?id=hvd.32044055015739&view=1up&seq=38&skin=2021), [Letter 359](https://babel.hathitrust.org/cgi/pt?id=chi.31115158&view=1up&seq=224&skin=2021)).~~

<hr>

Regarding “bl—y”: the text encodes it as:

- “bl” + word joiner + em dash + “y”

I changed it to:

- “bl” + word joiner + two‐em dash + word joiner + “y”

Is that correct?

### CODE REVIEW

**Comment by bentley** [comment]
Ignore my first paragraph; that decision is specifically mentioned in the release notes, so I deleted my commit changing it.

I did add a new commit that does two things:

- end every sequence of `‹` with `›` (instead of inconsistently using any of `»`, `’`, `›`)
- in the footnotes, refer to `‹` as “angle quote” instead of “turned comma” or “inverted comma”; that description was correct in the scans, but is incorrect now that we’re using a different symbol

**Comment by acabal** [comment]
I'm not clear on why we used angle quotes instead of lsquo or rsquo especially since the endnotes refer to inverted commas, which are the same as lsquo and rsquo. Angle quotes are pretty unusual in English prose. What are they in the page scans?

**Comment by bentley** [comment]
The scans use lsquo and rsquo (linked in the crossed‐out part of my earlier message).

In the original book, lsquo and rsquo were there to mark the paragraphs, as explained in the footnote:

> Those parts of this letter which are marked with an inverted comma (thus ‘) were afterwards transcribed by Miss Howe in Letter 373 written to the Ladies of <abbr>Mr.</abbr> Lovelace’s family; and are thus distinguished to avoid the necessity of repeating them in that letter.

I assume the SE producer chose to replace lsquo/rsquo with angle quotes because the marked paragraphs, while duplicated, are not “quoted text” as such. However, the SE producer only replaced the lsquo consistently, and only inconsistently replaced the corresponding rsquo, which is what f976cedb422daa517c45b907e54ad2779bb53cc4 fixes.

I see two options here:

1. Go back to the way of the original scan; use lsquo/rsquo, even though the paragraphs are not “quoted text” in the usual sense; leave original “upturned comma” wording in the footnotes; remove mention of angle quotes in the production notes. (Originally this pull request had a commit like that, because I overlooked the mention in the production notes and thus didn’t know using angle quotes was an intentional choice on the part of the SE producer.)
2. Commit to what the SE producer put in the release notes; use angle quotes; update “upturned comma” with a more appropriate descriptor; leave mention of angle quotes in the production notes. The pull request currently does this as of f976cedb422daa517c45b907e54ad2779bb53cc4.

I have no particular attachment to 1 or 2.

**Comment by bentley** [comment]
I suppose a third option might be to actually duplicate the paragraphs in our ebook, and remove the symbols altogether?

**Comment by acabal** [comment]
OK, I think this is a good approach. If we went with quotation marks, we would want to use double quotes instead of single quotes. But it's not a quotation per se so it could be confusing to the reader to do that. Angle quotes are unusual but a good alternative to indicate that it's not speech or quotation per se. Thanks!

**Pull request merged**
